# Generated by Django 3.1.7 on 2021-09-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('variant_id', models.CharField(max_length=255)),
                ('variant_title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
